## 의사결정나무
- 질문에 따라 판단
- 젤 위 루트 노드 -> 분할 -> 분할....
- 깊이가 짚어질 때 과적합이 발생할 위험이 크다.
- 분류 / 회귀 둘 다 가능

In [2]:
# 실습 폴더 불러오기
from pathlib import Path    
import warnings
warnings.filterwarnings('ignore')

DATA_DIR = Path('ml_실습데이터')
if not DATA_DIR.exists():
    DATA_DIR = Path('ml_실습데이터')
print(f'데이터 폴더: {DATA_DIR.resolve()}')

데이터 폴더: C:\Users\Administrator\bigdata2026\data_analysis\ml_실습데이터

### 라이브러리 불러오기

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
# export_text : 나무 구조를 글자로 출력
from sklearn.tree import DecisionTreeClassifier, export_text  # 의사결정나무 분류 
from sklearn.impute import SimpleImputer # 결측치를 특정 규칙에 따라 채워주는 전처리 도구
from sklearn.pipeline import make_pipeline # 여러 전처리 단계와 모델을 하나의 객체로 순서대로 연결

### 데이터 불러오기

In [4]:
df = pd.read_csv(DATA_DIR/'telecom_churn.csv')
df.head()

,usage_minutes,complaints,contract_months,monthly_fee,contract_type,region,churn
0,321.0,2,12,63.6,one-year,Gyeonggi,1
1,80.0,1,6,62.2,two-year,Gyeonggi,1
2,251.0,1,31,71.6,month-to-month,Other,0
3,158.0,0,31,58.8,two-year,Seoul,0
4,356.0,1,32,58.9,one-year,Gyeonggi,0

### 피처(입력), 타겟(정답) 데이터 나누기

In [5]:
# usage_minutes : 고객의 (월간) 통화/이용 시간 (분) -> 이용량이 급격히 줄어든 고객은 이미 다른 서비스로 떠났다.
# complaints : 고객이 접수한 불만/민원 건수 -> 서비스에 불만족해서 이탈할 확률이 높다고 판단
# contract_months : 계약 유지 기간(개월 수) -> 계약 기간이 짧을 수록 이탈 위험이 크다고 통신업계의 관찰
# monthly_fee : 월 요금 (청구액) -> 요금이 부담스러울수록 이탈 가능성이 있다. 
# churn : 타겟(정답), 이탈한다(1) / 안한다(0)
features = ['usage_minutes', 'complaints', 'contract_months', 'monthly_fee'] # 입력 컬럼
X = df[features]
y = df['churn']

X.shape, y.shape

((420, 4), (420,))

### 훈련 / 검증 데이터 나누기

In [6]:
X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((315, 4), (105, 4), (315,), (105,))

### 의사결정나무 분류 모델 학습시키기

In [7]:
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)  # 학습

DecisionTreeClassifier(random_state=42)

In [8]:
pred = model.predict(X_valid)  # 예측값

In [9]:
from sklearn.metrics import accuracy_score # 정확도

accuracy_score(y_valid, pred) # 정답과 예측을 비교해서 얼마나 정확한가?

0.5333333333333333

### 나무 깊이를 바꿔가며 훈련/검증 점수를 비교 -> 과적합 관찰

In [10]:
# 깊이를 2, 4, 제한없음(None) 세 가지로 바꿔가며 성능 비교
for depth in [2, 4, None]:
    model = make_pipeline(
        SimpleImputer(strategy='median'), # 결측치 패턴을 중앙값으로 채운다.
        DecisionTreeClassifier(max_depth=depth, random_state=42)
    )
    model.fit(X_train, y_train) # 학습
    pred = model.predict(X_valid)  # 예측
    print(f'{depth} -> {accuracy_score(y_valid, pred):.4f}') # 정확도 확인(소수 4째자리까지 확인)

2 -> 0.6952
4 -> 0.6476
None -> 0.5333

- 깊이가 없음(끝까지 내려가는 것)과 깊이 2이 성능이 서로 비슷하다면
- 깊이가 얕은 모델을 우선한다.

### 추가) 깊이가 2인 얕은 나무모델을 직접 뜯어보기

In [11]:
shallow = make_pipeline(
    SimpleImputer(strategy='median'),
    DecisionTreeClassifier(max_depth=2, random_state=42)
)
shallow.fit(X_train, y_train)

# named_steps: 파이프라인 안에서 이름으로 특정 단계(모델)를 꺼내오는 방법
tree_model = shallow.named_steps['decisiontreeclassifier']

print(export_text(tree_model, feature_names=features))

|--- complaints <= 1.50
|   |--- contract_months <= 12.50
|   |   |--- class: 0
|   |--- contract_months >  12.50
|   |   |--- class: 0
|--- complaints >  1.50
|   |--- monthly_fee <= 32.75
|   |   |--- class: 0
|   |--- monthly_fee >  32.75
|   |   |--- class: 1

In [12]:
shallow

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                ('decisiontreeclassifier',
                 DecisionTreeClassifier(max_depth=2, random_state=42))])

In [13]:
shallow.named_steps

{'simpleimputer': SimpleImputer(strategy='median'),
 'decisiontreeclassifier': DecisionTreeClassifier(max_depth=2, random_state=42)}

## 여러 모델의 의견을 모으는 앙상블
- 랜덤포레스트 --> 데이터를 무작위로 복원추출(부트스트랩), 
            각 분할마다 특성도 무작위로 일부만 사용해서 서로 다른 나무 여러 개를 만든 뒤 평균/다수결로 예측
            단일 나무보다 과적합에 강하지만, 개별 나무 하나하를 사람이 읽고 설명하지는 어려워진다라는
            트레이드오프가 있다.
            '여러 사람에게 물어보고 다수결로 정한다'라는 비유
            분류 / 회귀 둘 다 가능
            분산 처리(배깅) 다수결(보팅)

### 라이브러리 불러오기

In [14]:
from sklearn.ensemble import RandomForestClassifier # 여러 개의 의사결정나무를 모아 만드는 앙상블 모델
from sklearn.metrics import f1_score  # 정밀도와 재현율의 조화평균(불균형 데이터에 적합하다)

In [15]:
df = pd.read_csv(DATA_DIR/'telecom_churn.csv')
features

['usage_minutes', 'complaints', 'contract_months', 'monthly_fee']

In [16]:
# 입력(피처), 정답(타겟) --> 훈련/검증 나누기
X = df[features]
y = df['churn']
X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.25, stratify=y, random_state=42
)
X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((315, 4), (105, 4), (315,), (105,))

In [17]:
model = RandomForestClassifier(
    n_estimators=200,  # 나무가 200그루
    max_depth=5,
    random_state=42
)

# 학습
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42)

In [18]:
# 예측
pred = model.predict(X_valid)

# 평가 - 정확도
print(f'랜덤포레스트 분류의 정확도: {accuracy_score(y_valid, pred):.4f}')

랜덤포레스트 분류의 정확도: 0.6476

### 의사결정나무와 랜덤포레스트 비교

In [19]:
models = {
    'tree': DecisionTreeClassifier(max_depth=4, random_state=42),
    'forest': RandomForestClassifier(n_estimators=200, max_depth=4, random_state=42)
}
models.keys()

dict_keys(['tree', 'forest'])

In [20]:
models.values()

dict_values([DecisionTreeClassifier(max_depth=4, random_state=42), RandomForestClassifier(max_depth=4, n_estimators=200, random_state=42)])

In [21]:
models.items() #  튜플로 쌍을 묶는다

dict_items([('tree', DecisionTreeClassifier(max_depth=4, random_state=42)), ('forest', RandomForestClassifier(max_depth=4, n_estimators=200, random_state=42))])

In [22]:
fitted = {}
for name, estimator in models.items():
    pipe = make_pipeline(SimpleImputer(strategy='median'), estimator)
    pipe.fit(X_train, y_train)  # 학습
    fitted[name] = pipe  # 나중에 다시 꺼내쓰기 위해서 딕셔너리에 저장
    pred = pipe.predict(X_valid) # 예측
    print(f'{name} F1 score: {f1_score(y_valid, pred):.4f}')  # f1 score(조화평균) 확인
    print(f'{name} 정확도: {accuracy_score(y_valid, pred):.4f}')  # 정확도 확인

tree F1 score: 0.4127
tree 정확도: 0.6476
forest F1 score: 0.4000
forest 정확도: 0.6571

In [23]:
fitted

{'tree': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                 ('decisiontreeclassifier',
                  DecisionTreeClassifier(max_depth=4, random_state=42))]),
 'forest': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                 ('randomforestclassifier',
                  RandomForestClassifier(max_depth=4, n_estimators=200,
                                         random_state=42))])}

### 랜덤포레스트가 어떤 특성을 중요하게 봤는지 확인

In [24]:
forest = fitted['forest'].named_steps['randomforestclassifier']

In [25]:
importance = forest.feature_importances_  #  특성 중요도
importance

array([0.20330039, 0.3036125 , 0.26338513, 0.22970198])

In [26]:
features

['usage_minutes', 'complaints', 'contract_months', 'monthly_fee']

In [30]:
df2 = pd.DataFrame(
    data=importance,
    index=features,
    columns=['특성 중요도']
)
df2.sort_values('특성 중요도', ascending=False)

                   특성 중요도
complaints       0.303612
contract_months  0.263385
monthly_fee      0.229702
usage_minutes    0.203300

In [ ]:
df_importance = pd.DataFrame({
    '특성(컬럼)': features,
    '중요도': importance,
})
df_importance

            특성(컬럼)       중요도
0    usage_minutes  0.203300
1       complaints  0.303612
2  contract_months  0.263385
3      monthly_fee  0.229702

In [35]:
# 나무 수를 50으로 바꾸고, 정확도, f1-score구하기
model_50 = RandomForestClassifier(
    n_estimators=50,
    max_depth=5,
    random_state=42
)
model_50.fit(X_train, y_train)
pred_50 = model_50.predict(X_valid)
acc_50 = accuracy_score(y_valid, pred_50)
print(f'정확도: {acc_50:.4f}')

f1_50 = f1_score(y_valid, pred_50)
print(f'f1 스코어: {f1_50:.4f}')

df_50 = pd.DataFrame(data=model_50.feature_importances_,
                     index=features,
                     columns=['나무 50개일 때 특성 중요도'])
df_50.sort_values(by='나무 50개일 때 특성 중요도', ascending=False)

정확도: 0.6476
f1 스코어: 0.4127

                 나무 50개일 때 특성 중요도
monthly_fee              0.309272
contract_months          0.238881
complaints               0.236786
usage_minutes            0.215061